

INCLUDES =  -I .\\  -I..\inc\\  -I..\neowayinc\\

OBJS = example_helloWorld.o map.o app_start.o neoway_message.o neoway_analysis_sms.o user.o at_init.o ble.o http.o fota.o



all:listobj $(OBJS)


include ..\makefiledef
